name: Test

on:
  push:
    branches:
      - develop

jobs:

  test:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Execute Gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Build APK
        run: ./gradlew assembleDebug bundleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/bundle/debug/*.aab
