
name: Test



on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  validation:
    name: Validation
    runs-on: macos-latest
    steps:
      -  uses: actions/checkout@v3
      -  uses: gradle/wrapper-validation-action@v1

  build-test:
    name: Build test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build --stacktrace

  test:
    name: Test
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run tests
        run: ./gradlew test

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Build APK
        run: ./gradlew assembleDebug bundleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/bundle/debug/*.aab
